import { createFileRoute } from "@tanstack/react-router";
import { LogOut, Pencil, Plus, Trash2, Upload, X } from "lucide-react";
import { useEffect,useState } from "react";
import { deleteProduct,isAdmin,listProducts,saveProduct,signIn,signOut,session,uploadImage,type Product } from "../lib/supabase";
export const Route=createFileRoute("/admin")({component:Admin});
function Admin(){
 const [authed,setAuthed]=useState(false),[email,setEmail]=useState("joaovitorsouzaoficial299@gmail.com"),[password,setPassword]=useState(""),[products,setProducts]=useState<Product[]>([]),[error,setError]=useState(""),[editing,setEditing]=useState<Partial<Product>|null>(null),[loading,setLoading]=useState(true);
 const refresh=()=>listAdminProducts().then(setProducts);
 useEffect(()=>{isAdmin().then(ok=>{setAuthed(ok);if(ok)refresh()}).finally(()=>setLoading(false))},[]);
 async function login(e:React.FormEvent){e.preventDefault();setError("");try{await signIn(email,password);if(!await isAdmin())throw new Error("Este usuário não está autorizado como administrador.");setAuthed(true);await refresh()}catch(err){setError(err instanceof Error?err.message:"Erro ao entrar.")}}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;try{await saveProduct({...editing,price:Number(editing.price||0),discount_percent:Number(editing.discount_percent||0),stock:Number(editing.stock||0),available:editing.available!==false},editing.id);setEditing(null);await refresh()}catch(err){setError(err instanceof Error?err.message:"Erro ao salvar.")}}
 if(loading)return <main className="admin-page"><div className="admin-loading">LIFE STORE / ADMIN</div></main>;
 if(!authed)return <main className="admin-page"><div className="admin-login"><a href="/" className="admin-mark">LS</a><span>PAINEL ADMINISTRATIVO</span><h1>ACESSO<br/><em>LIFE STORE.</em></h1><form onSubmit={login}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha"/><button>ENTRAR</button></form>{error&&<p className="admin-error">{error}</p>}<small>O acesso usa a autenticação do Supabase. O administrador de teste é o e-mail configurado para a Life Store.</small></div></main>;
 return <main className="admin-page"><header className="admin-header"><a href="/" className="admin-mark">LS</a><div><span>PAINEL</span><h1>CATÁLOGO LIFE STORE</h1></div><button onClick={()=>{signOut();setAuthed(false)}}><LogOut size={16}/> Sair</button></header><section className="admin-content"><div className="admin-toolbar"><div><span>PRODUTOS</span><strong>{products.length}</strong></div><button onClick={()=>setEditing({name:"",description:"",price:0,discount_percent:0,stock:0,category:"",image_url:"",available:true})}><Plus size={17}/> Novo produto</button></div><div className="admin-list">{products.map(p=><article key={p.id}><div className="admin-thumb">{p.image_url?<img src={p.image_url} alt=""/>:<span>LS</span>}</div><div><h2>{p.name}</h2><p>R$ {p.price.toFixed(2).replace(".",",")} · estoque {p.stock} · {p.available?"disponível":"esgotado"}</p></div><div className="admin-actions"><button onClick={()=>setEditing(p)}><Pencil size={16}/></button><button onClick={async()=>{if(confirm("Excluir este produto?")){await deleteProduct(p.id);refresh()}}}><Trash2 size={16}/></button></div></article>)}</div></section>{editing&&<div className="admin-modal"><form onSubmit={save}><button type="button" className="modal-close" onClick={()=>setEditing(null)}><X/></button><span>PRODUTO</span><h2>{editing.id?"Editar produto":"Novo produto"}</h2><input required placeholder="Nome" value={editing.name||""} onChange={e=>setEditing({...editing,name:e.target.value})}/><textarea placeholder="Descrição" value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})}/><div className="admin-row"><input type="number" step="0.01" placeholder="Preço" value={editing.price??0} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/><input type="number" placeholder="Desconto %" value={editing.discount_percent??0} onChange={e=>setEditing({...editing,discount_percent:Number(e.target.value)})}/><input type="number" placeholder="Estoque" value={editing.stock??0} onChange={e=>setEditing({...editing,stock:Number(e.target.value)})}/></div><input placeholder="Categoria" value={editing.category||""} onChange={e=>setEditing({...editing,category:e.target.value})}/><label className="upload-box"><Upload size={18}/>Adicionar foto<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f){try{setEditing({...editing,image_url:await uploadImage(f)})}catch(err){setError(err instanceof Error?err.message:"Erro no upload.")}}}}/></label>{editing.image_url&&<img className="modal-preview" src={editing.image_url} alt="Prévia do produto"/>}<label className="toggle-row"><input type="checkbox" checked={editing.available!==false} onChange={e=>setEditing({...editing,available:e.target.checked})}/> Disponível para venda</label>{error&&<p className="admin-error">{error}</p>}<button className="save-product">SALVAR PRODUTO</button></form></div>}</main>
}
